
workflows:
  my-workflow:
    name: example_new_project
    instance_type: asus_vivobook
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter test
      - flutter build apk
    artifacts:
      - build/**/outputs/**/*.apk
